# This is a basic workflow to help you get started with Actions
name: CI-CD

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o DockerHub
        uses: docker/login-action@v2.0.0
        with:        
          username: ${{secrets.DOCKERHUB_USER}}     
          password: ${{secrets.DOCKERHUB_PWD}}
        
      - name: Construindo a imagem e mandando para o DockerHub
        uses: docker/build-push-action@v3.1.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            thaynafonseca/kube-news:latest
            thaynafonseca/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3  
     
      - name: Definindo o cluster Kubernetes
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}} 
        
      
      - name: Efetuando o deployment
        uses: Azure/k8s-deploy@v4.3
        with:
          images: thaynafonseca/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
